### ISSUE TITLE
Don't pad the editor with new lines

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/so-css#40]
Padding the editor with new lines feels a little messy to me. It means you have to be more accurate about where you click when you want to get to the end of a file, and we might be encouraging users to add extra spacing into their code.

Ideally, we should just have a single line added, and make clicking anywhere in the editor, or the editor wrapper, move the cursor to this line.

**Comment by braamgenis** [comment]
This has since been resolved. The reason for this was that CodeMirror only recognizes right-clicks for pasting when clicking on an editable line. So now in an empty editor you have to click on the first line (the only editable line) to paste whatever is on the clipboard. I'll add a different issue for this.
